**AIM**:

To solve the Transportation Problem for minimizing the cost of transporting goods from multiple
sources to multiple destinations using Python.

PROCEDURE:
1. Install Required Libraries:
o Make sure you have numpy and scipy installed. You can install them using pip if
not already installed.
bash
Copy code
pip install numpy scipy
2. Define the Problem:
o Identify the cost matrix, supply array, and demand array.
3. Set Up the Problem in Python:
o Use the scipy.optimize.linprog function to set up and solve the Transportation
Problem.
4. Run the Code:
o Execute the Python code to get the optimized result.
5. Analyze the Output:
o Interpret the results and validate the solution against the problem constraints.

In [ ]:
import numpy as np
from scipy.optimize import linprog

# Cost matrix (sources × destinations)
cost = np.array([
    [4, 8, 8],
    [2, 7, 6],
    [3, 4, 2]
])

# Flatten cost matrix for linprog
c = cost.flatten()

# Supply and demand
supply = np.array([50, 40, 60])
demand = np.array([30, 70, 50])

# Equality constraints (supply and demand must be satisfied)
A_eq = []
b_eq = []

# Supply constraints: each source distributes exactly its supply
for i in range(len(supply)):
    constraint = [0] * len(c)
    for j in range(len(demand)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(supply[i])

# Demand constraints: each destination receives exactly its demand
for j in range(len(demand)):
    constraint = [0] * len(c)
    for i in range(len(supply)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(demand[j])

# Solve transportation problem
result = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=(0, None), method='highs')

# Reshape result to original matrix shape
result_matrix = result.x.reshape(cost.shape)

# Print results
print('Optimal value (total cost):', result.fun)
print('Optimal transport plan:')
print(result_matrix)


Optimal value (total cost): 670.0
Optimal transport plan:
[[ 0. 50.  0.]
 [30. 10.  0.]
 [ 0. 10. 50.]]
